-- ============================================================================
-- Snowflake Database & Warehouse Setup Script for Modern Data Stack Pipeline
-- ============================================================================

-- 1. Create Roles
CREATE ROLE IF NOT EXISTS DATA_ENGINEER;
CREATE ROLE IF NOT EXISTS DBT_ROLE;

-- 2. Create Warehouses
CREATE WAREHOUSE IF NOT EXISTS INGEST_WH
    WITH WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Warehouse dedicated to raw ingestion API loads';

CREATE WAREHOUSE IF NOT EXISTS TRANSFORM_WH
    WITH WAREHOUSE_SIZE = 'SMALL'
    AUTO_SUSPEND = 120
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Warehouse dedicated to dbt transformations';

-- 3. Create Databases
CREATE DATABASE IF NOT EXISTS RAW_DB COMMENT = 'Raw landed JSON datasets';
CREATE DATABASE IF NOT EXISTS ANALYTICS_DB COMMENT = 'Transformed enterprise analytics data warehouse';

-- 4. Create Schemas
CREATE SCHEMA IF NOT EXISTS RAW_DB.BRONZE COMMENT = 'Bronze raw payload landing tables';
CREATE SCHEMA IF NOT EXISTS ANALYTICS_DB.SILVER COMMENT = 'Silver cleansed & deduplicated tables';
CREATE SCHEMA IF NOT EXISTS ANALYTICS_DB.GOLD COMMENT = 'Gold Kimball dimensional star schema';

-- 5. Create Raw Tables
CREATE TABLE IF NOT EXISTS RAW_DB.BRONZE.RAW_USERS (
    raw_payload VARIANT,
    ingested_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RAW_DB.BRONZE.RAW_EVENTS (
    raw_payload VARIANT,
    ingested_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 6. Role Grants & Permissions
GRANT USAGE ON WAREHOUSE INGEST_WH TO ROLE DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE DBT_ROLE;

GRANT ALL ON DATABASE RAW_DB TO ROLE DATA_ENGINEER;
GRANT ALL ON SCHEMA RAW_DB.BRONZE TO ROLE DATA_ENGINEER;

GRANT USAGE ON DATABASE RAW_DB TO ROLE DBT_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA RAW_DB.BRONZE TO ROLE DBT_ROLE;

GRANT ALL ON DATABASE ANALYTICS_DB TO ROLE DBT_ROLE;
GRANT ALL ON SCHEMA ANALYTICS_DB.SILVER TO ROLE DBT_ROLE;
GRANT ALL ON SCHEMA ANALYTICS_DB.GOLD TO ROLE DBT_ROLE;
